version: '3.8'

services:
  web:
    build: ./boda_web_final
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./boda_web_final/:/usr/src/boda_web_final/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=boda_docker
      - POSTGRES_PASSWORD=boda_docker
      - POSTGRES_DB=boda_docker_dev

volumes:
  postgres_data: